var mapping = {
// '163': 'onesixtythree.js',
// '8tracks': 'eighttracks.js',
// '22tracks': '22tracks.js',
// '99percentinvisible' : 'scm.js',
// 'amazon': 'amazon.js',
// 'app.napster': 'napster.js',
// 'audible': 'audible.js',
// 'audiogalaxy': 'audiogalaxy.js',
// 'audiomack': 'audiomack.js',
// 'bandcamp': 'bandcamp.js',
// 'bbc': 'bbcradiopopout.js',
// 'beatsmusic': 'beatsmusic.js',
// 'bop': 'bop.js',
// 'bronytunes': 'bronytunes.js',
// 'cliggo': 'cliggo.js',
// 'connect.monstercat': 'monstercat.js',
// 'deezer': 'deezer.js',
// 'di.fm': 'di.js',
// 'dr.dk': 'dr.js',
// 'dreamfm': 'dreamfm.js',
// 'earbits': 'earbits.js',
// 'ex.fm': 'exfm.js',
// 'feedly': 'feedly.js',
// 'focusatwill': 'focusatwill.js',
// 'gaana': 'gaana.js',
// 'getworkdonemusic': 'getworkdone.js',
// 'giantbomb': 'giantbomb.js',
// 'gold.monstercat': 'monstercat.js',
// 'grooveshark': 'grooveshark.js',
// 'hearthis': 'hearthis.js',
// 'hypem': 'hypemachine.js',
// 'iheart': 'iheart.js',
// 'indieshuffle': 'indieshuffle.js',
// 'jango': 'jango.js',
// 'jing.fm': 'jingfm.js',
// 'last': 'lastfm.js',
// 'license.monstercat': 'monstercat.js',
// 'mixcloud': 'mixcloud.js',
// 'mixrad': 'nokiamixradio.js',
// 'mog': 'mog.js',
// 'music.microsoft': 'xbox.js',
// 'netflix': 'netflix.js',
// 'noonpacific': 'noonpacific.js',
// 'one.npr': 'nprone.js',
// 'overcast': 'overcast.js',
// 'pandora': 'pandora.js',
'play.google': 'googleplaymusic.js',
// 'player.fm': 'playerfm.js',
// 'playlist.com': 'playlist.js',
// 'playlist.me': 'scm.js',
// 'pleer.com': 'pleer.js',
// 'plex': 'plex.js',
// 'pocketcasts.com': 'pocketcasts.js',
// 'poolside': 'poolside.js',
// 'pony.fm': 'ponyfm.js',
// 'ponyvillelive': 'ponyvillelive.js',
// 'rbmaradio': 'rbma.js',
// 'rdio': 'rdio.js',
// 'reddit.music.player.il.ly': 'redditplayer.js',
// 'reddit.musicplayer.io': 'redditplayer.js',
// 'rhapsody': 'rhapsody.js',
// 'saavn': 'saavn.js',
// 'scribd': 'scribd.js',
// 'scmplayer': 'scmframeless.js',
// 'shuffler': 'shuffler.js',
// 'slacker': 'slacker.js',
// 'songdrop': 'songdrop.js',
// 'songza': 'songza.js',
// 'soundcloud': 'soundcloud.js',
// 'soundtracker': 'soundtracker.js',
// 'spotify': 'spotify.js',
// 'smule': 'smule.js',
// 'stitcher': 'stitcher.js',
// 'subsonic': 'subsonic.js',
// 'sverigesradio': 'sverigesradio.js',
// 'themusicninja': 'themusicninja.js',
// 'thesixtyone': 'thesixtyone.js',
// 'thisismyjam': 'thisismyjam.js',
// 'tracksflow': 'tracksflow.js',
// 'tumblr': 'scm.js',
// 'tunein': 'tunein.js',
// 'turntable': 'turntable.js',
// 'twitter': 'twitter.js',
// 'vessel': 'vessel.js',
// 'vimeo': 'vimeo.js',
// 'vk': 'vk.js',
// 'wearehunted': 'wearehunted.js',
// 'y.qq': 'qqmusic.js',
// 'music.yandex': 'yandexmusic.js',
// 'radio.yandex': 'yandexradio.js',
'youtube': 'youtube.js',
// 'albumkings': 'albumkings.js',
// 'itunes.apple.com': 'applemusic.js',
}

var findStrategy = function(url) {
  for (var strategy in mapping) {
    if (url.indexOf(strategy) != -1) {
      return mapping[strategy]
    }
  }
}

module.exports = { mapping, findStrategy }
